name: Generate API Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Documentation (phpDocumentor)
        run: |
          docker run --rm -v ${{ github.workspace }}:/data phpdoc/phpdoc:3 \
            -d ./Backend/src/app \
            -t ./Backend/public-docs \
            --template="clean"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './Backend/docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
